AWSTemplateFormatVersion: '2010-09-09'
Description: List AWS Linux AMI for CFN and other automation tools
Parameters:
  CacheTtl:
    Default: 1800000
    Description: AMI cache timeout
    Type: Number
Resources:
  CollectAmi:
    Properties:
      CodeUri: s3://net.clifflu.sls-deploy.us-west-2/b9b3ea369b7904e9717ff93ff4cbc03c
      Environment:
        Variables:
          TTL:
            Ref: CacheTtl
      Events:
        PutResource:
          Properties:
            Method: get
            Path: /ami
          Type: Api
      Handler: index.collectAmi
      MemorySize: 320
      Policies:
        Statement:
        - Action: ec2:DescribeImages
          Effect: Allow
          Resource: '*'
      Runtime: nodejs6.10
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
